Repository say-node-to-drugs/ResonArt, pull requests merged in 2019-02, with the labels that each got.

#50 fix (palette): refactored code to split up larger functions
  client/components/sketches/PaletteSketch.js
Labels: Chore

#51 fix (palette): notes played while drawing match the scales played back
  client/components/sketches/PaletteSketch.js
Labels: bug

#52 fix (palette): timing now matches the drums and bpm can be changed
  client/components/Studio.js
  client/components/sketches/DrumSketch.js
  client/components/sketches/PaletteSketch.js
Labels: bug

#53 fix (palette): fixed a few bugs. red paint now works
  client/components/sketches/PaletteSketch.js
Labels: bug

#58 fix (palette): fixed bug from previous pull request
  client/components/sketches/PaletteSketch.js
Labels: bug

#65 feature (palette): added new instrument(blue) and added save image bu…
  client/components/sketches/PaletteSketch.js
Labels: enhancement

#66 Set up paletteSketch and Studio to use the firebase instance the user created.
  client/app.js
  client/components/Studio.js
  client/components/login-signup/SignInFacebook.js
  client/components/login-signup/SignInGoogle.js
  client/components/login-signup/SignInTwitter.js
  client/components/login-signup/SignUpIndex.js
  client/components/navbar.js
  client/components/sketches/PaletteSketch.js
  client/firebase/loadCanvas.js
  client/firebase/loadCanvasCopy.js
  client/firebase/preloadBlankCanvas.js
  client/firebase/saveCanvas.js
  server/index.js
Labels: enhancement

#71 feature (download): added download audio functionality
  client/components/sketches/PaletteSketch.js
Labels: enhancement

#73 fix (download): fixed the download feature
  client/components/sketches/PaletteSketch.js
Labels: bug

#80 fix (download): fixed the download audio functionality
  client/components/sketches/PaletteSketch.js
Labels: bug

#83 fix (palette): merge conflict was fixed
  client/components/sketches/PaletteSketch.js
Labels: bug

#85 fix (palette): resizeing the page now works
  client/components/sketches/PaletteSketch.js
Labels: bug

#87 fix (eraser): eraser function is more accurate
  client/components/sketches/PaletteSketch.js
Labels: bug

#91 feature (landing page): landing page now shows one preset canvas
  client/app.js
  client/components/LandingPage.js
  client/components/sketches/PaletteSketch.js
Labels: enhancement

#92 fix (landing page): fixed bugs from last pull request
  client/components/LandingPage.js
  client/components/sketches/PaletteSketch.js
Labels: bug

#93 fix (landing page): clicking on preset palette on landing page routes…
  client/components/LandingPage.js
  client/components/Studio.js
  client/components/sketches/PaletteSketch.js
Labels: bug

#96 fix (app.js): fixed small bug that prevented building
  client/app.js
Labels: bug

#99 fix (landing page): loading a preset canvas now properly loads synths…
  client/components/LandingPage.js
  client/components/sketches/PaletteSketch.js
Labels: bug

#102 feature (scales): there are now buttons to switch between scales
  client/components/LandingPage.js
  client/components/Studio.js
  client/components/login-signup/AccountIndex.js
  client/components/sketches/PaletteSketch.js
  public/style.css
Labels: enhancement

#105 fix (clear button): clear button now works properly
  client/components/sketches/PaletteSketch.js
  public/style.css
Labels: bug
